## Path to sample sheet
samplesheet: 'ChIPsamplesheet.txt'

## List columns to concatenate for file names 
## (or indicate a single Name column, i.e. fileNamesFrom: ['Name'])
fileNamesFrom: ['Project', 'Cell_Type', 'Target', 'Time', 'Bio_Rep', 'Tech_Rep']

## List columns to group (i.e. any columns left out will become part of the same group)
## set mergeBy: '' for no merging
mergeBy: ['Project', 'Cell_Type', 'Target', 'Time']

## Indicate whether to create stranded signal tracks
stranded: True # False

## Genome-specific reference parameters
bwamem: '/proj/seq/data/HG19_UCSC/Sequence/BWAIndex/genome.fa'

## Software versions
fastqcVers: "0.11.5"
trimVers: "0.4.3"
bwaVers: "0.7.17"
samtoolsVers: "1.9"
javaVers: "10.0.2"
deeptoolsVers: "3.0.1"
multiqcVers: "1.5" 
bedtoolsVers: "2.26"
macsVers: "2016-02-15"
